In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('diotali.csv', sep=';')
df.head()

  ct_numero    uo_libelle
0     64149  DAKAR VISION
1     64150  DAKAR VISION
2     64151  DAKAR VISION
3     64152  DAKAR VISION
4     64153  DAKAR VISION

In [4]:
df2 = pd.read_excel('RESUMER.xlsx')
df2.head()

  Client  Numero   Matricule
0   3FPT   32659  AD2994TTD1
1   3FPT   32660     AD30801
2   3FPT   32681    AD293960
3   3FPT   32697    AD294000
4   3FPT   32698    AD293950

In [11]:
df2["present"] = df2["Numero"].isin(df["ct_numero"]).map({True: "oui", False: "non"})
df2.head()

  Client  Numero   Matricule present
0   3FPT   32659  AD2994TTD1     oui
1   3FPT   32660     AD30801     oui
2   3FPT   32681    AD293960     oui
3   3FPT   32697    AD294000     oui
4   3FPT   32698    AD293950     oui

In [12]:
df2_absents = df2[df2["present"] == "non"]
df2_absents

     Client  Numero  Matricule present
9      3FPT  109954   AD293970     non
18     AEGF  134621    AA020BM     non
44     ANAM  116088    AD0215.     non
45     ANAM  116098     AD0213     non
46     ANAM  121360     AD5711     non
...     ...     ...        ...     ...
4179    TAD  118809    TH4730E     non
4180    TAD  118810    AA348HP     non
4181    TAD  118811  AA 977 FV     non
4182    TAD  118812    AA236VJ     non
4183    TAD  118815    AA647ML     non

[605 rows x 4 columns]

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4558 entries, 0 to 4557
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ct_numero   4558 non-null   object
 1   uo_libelle  4558 non-null   object
dtypes: object(2)
memory usage: 71.3+ KB

In [8]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4272 entries, 0 to 4271
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Client     4272 non-null   object
 1   Numero     4272 non-null   int64
 2   Matricule  4272 non-null   object
 3   present    4272 non-null   object
dtypes: int64(1), object(3)
memory usage: 133.6+ KB

In [10]:
df["ct_numero"] = pd.to_numeric(df["ct_numero"], errors="coerce").astype("Int64")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4558 entries, 0 to 4557
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ct_numero   4557 non-null   Int64
 1   uo_libelle  4558 non-null   object
dtypes: Int64(1), object(1)
memory usage: 75.8+ KB

In [13]:
df2_absents.to_csv('absents.csv', index=False)